services: 
  api:
    build:
      context: .
      target: production
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 4000:4000
      env_file:
      - .env